version: "3.2"
volumes:
  ustcflyer_nginx_ssl:
  ustcflyer_certbot_certs:
  ustcflyer_com_certbot:
  postgres-data-volume:
  backend-static-volume:

services:
  backend:
    build: ./backend/
    environment:
      POSTGRES_DB: flyers
      POSTGRES_USER: postgres
      POSTGRES_PWD: ${POSTGRES_PASSWORD}
      DJANGO_SETTINGS_MODULE: flyers.settings.prod
    volumes:
      - backend-static-volume:/app/backend/static
    ports:
      - 8000
      - 5678
    depends_on:
      - postgres

  postgres:
    build: 
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: flyers
      POSTGRES_HOST: "%"
    ports:
      - 5432
    volumes:
      - postgres-data-volume:/var/lib/postgres

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
        - /var/opt/pgbackups:/backups
    links:
        - postgres
    depends_on:
        - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: flyers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_PASSWORD_FILE: /run/secrets/db_password <-alternative for POSTGRES_PASSWORD (to use with docker secrets)
      POSTGRES_EXTRA_OPTS: -Z6 --schema=public --blobs
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: 8008
      SCHEDULE: "@midnight"
    ports:
      - 8008

  nginx:
    build: ./
    links:
      - backend
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - backend-static-volume:/app/backend/static
      - ustcflyer_nginx_ssl:/etc/nginx/ssl
      - ustcflyer_certbot_certs:/etc/letsencrypt
      - ustcflyer_com_certbot:/var/www/certbot/ustcflyer.com
    ports:
      - 80
      - 443
    env_file:
      - ./docker/config.env
    environment:
      NODE_ENV: production
    restart: always

  certbot:
    build: ./docker/certbot
    image: ustcflyer/certbot
    env_file:
      - ./docker/config.env
    volumes:
      - ustcflyer_certbot_certs:/etc/letsencrypt
      - ustcflyer_com_certbot:/var/www/certbot/ustcflyer.com
    depends_on:
      - nginx

  cron:
    build: ./docker/cron
    environment:
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workdir:ro
    depends_on:
      - nginx
      - certbot