version: "3.2"
volumes:
  postgres-data-volume:

services:
  backend:
    build: ./backend/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 666666
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5959:5959
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 666666
      POSTGRES_DB: postgres
      POSTGRES_HOST: "%"
    ports:
      - 5432:5432
    volumes:
      - postgres-data-volume:/var/lib/postgres

  # nginx:
  #   build: ./
  #   links:
  #     - backend
  #   volumes:
  #     - ./docker/nginx:/etc/nginx/conf.d
  #     - backend-static-volume:/app/backend/static
  #   ports:
  #     - 2000:80
  #   environment:
  #     NODE_ENV: production