version: "3.2"
volumes:
  postgres-data-volume:
  backend-static-volume:

services:
  backend:
    build: ./backend/
    environment:
      POSTGRES_DB: flyers
      POSTGRES_USER: postgres
      POSTGRES_PWD: ${POSTGRES_PASSWORD}
      DJANGO_SETTINGS_MODULE: flyers.settings.prod
    volumes:
      - backend-static-volume:/app/backend/static
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    build: 
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: flyers
      POSTGRES_HOST: "%"
    ports:
      - 5432:5432
    volumes:
      - postgres-data-volume:/var/lib/postgres

  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
        - /var/opt/pgbackups:/backups
    links:
        - postgres
    depends_on:
        - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: flyers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_PASSWORD_FILE: /run/secrets/db_password <-alternative for POSTGRES_PASSWORD (to use with docker secrets)
      POSTGRES_EXTRA_OPTS: -Z6 --schema=public --blobs
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: 8008
      SCHEDULE: "@midnight"
    ports:
      - 8008:8008

  nginx:
    build: ./
    links:
      - backend
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - backend-static-volume:/app/backend/static
    ports:
      - 8080:80
    environment:
      NODE_ENV: production