# Generated by Django 3.1.7 on 2021-03-29 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=256)),
                ('school_name', models.CharField(max_length=256)),
                ('school_name_cn', models.CharField(max_length=256)),
                ('short_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('full_name', models.CharField(max_length=256)),
                ('related_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.university', verbose_name='related_university')),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.IntegerField(choices=[('045：数学系', '045：数学系'), ('046：计算与应用数学系', '046：计算与应用数学系'), ('047：概率统计系', '047：概率统计系'), ('002：物理学系', '002：物理学系'), ('004：近代物理系', '004：近代物理系'), ('022：天文学系', '022：天文学系'), ('038：光学与光学工程系', '038：光学与光学工程系'), ('048：工程与应用物理系', '048：工程与应用物理系'), ('015：工商管理系', '015：工商管理系'), ('016：管理科学系', '016：管理科学系'), ('017：统计与金融系', '017：统计与金融系'), ('034：MBA中心', '034：MBA中心'), ('035：MPA中心', '035：MPA中心'), ('039：EMBA', '039：EMBA'), ('003：化学物理系', '003：化学物理系'), ('012：应用化学系', '012：应用化学系'), ('014：材料科学与工程系', '014：材料科学与工程系'), ('019：化学系', '019：化学系'), ('020：高分子科学与工程系', '020：高分子科学与工程系'), ('008：分子生物学与细胞生物学系', '008：分子生物学与细胞生物学系'), ('021：神经生物学与生物物理学系', '021：神经生物学与生物物理学系'), ('031：系统生物学系', '031：系统生物学系'), ('032：医药生物技术系', '032：医药生物技术系'), ('071：地球物理与行星科学技术系', '071：地球物理与行星科学技术系'), ('072：地球化学与环境科学系', '072：地球化学与环境科学系'), ('005：近代力学系', '005：近代力学系'), ('009：精密机械与精密仪器系', '009：精密机械与精密仪器系'), ('013：热科学和能源工程系', '013：热科学和能源工程系'), ('030：安全科学与工程系', '030：安全科学与工程系'), ('006：电子工程与信息科学系', '006：电子工程与信息科学系'), ('010：自动化系', '010：自动化系'), ('023：电子科学与技术系', '023：电子科学与技术系'), ('033：信息安全', '033：信息安全'), ('018：外语系', '018：外语系'), ('024：科技史与科技考古系', '024：科技史与科技考古系'), ('025：科技传播与科技政策系', '025：科技传播与科技政策系'), ('055：科技哲学系', '055：科技哲学系'), ('056：心理学系', '056：心理学系'), ('011：计算机科学与技术系', '011：计算机科学与技术系'), ('044：物流工程硕士中心', '044：物流工程硕士中心')])),
                ('gpa', models.FloatField()),
                ('rank', models.IntegerField(choices=[('top1%', 'top1%'), ('top5%', 'top5%'), ('top10%', 'top10%'), ('top30%', 'top30%'), ('top50%', 'top50%'), ('else', 'else')])),
                ('TOEFL', picklefield.fields.PickledObjectField(editable=False)),
                ('GRE', picklefield.fields.PickledObjectField(editable=False)),
                ('researchTag', multiselectfield.db.fields.MultiSelectField(choices=[('oversea_research', 'oversea_research'), ('paper', 'paper'), ('first_author', 'first_author'), ('internship', 'internship')], max_length=46)),
                ('researchSpec', models.CharField(max_length=1024)),
                ('referTag', multiselectfield.db.fields.MultiSelectField(choices=[('oversea_refer', 'oversea_refer'), ('connection', 'connection')], max_length=24)),
                ('applyFor', multiselectfield.db.fields.MultiSelectField(choices=[('ms', 'ms'), ('phd', 'phd'), ('ms_phd', 'ms_phd')], max_length=13)),
                ('summary', models.CharField(max_length=1024)),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='related user')),
            ],
        ),
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=256)),
                ('program', models.CharField(max_length=256)),
                ('result', models.BooleanField()),
                ('enrolledSemester', models.CharField(max_length=256)),
                ('comments', models.CharField(max_length=1024)),
                ('tag', multiselectfield.db.fields.MultiSelectField(choices=[('admitted', 'admitted'), ('reject', 'reject'), ('waitlist', 'waitlist')], max_length=24)),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='related user')),
            ],
        ),
    ]
