# Generated by Django 3.1.7 on 2021-04-16 07:24

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'ms')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=256)),
                ('school_name', models.CharField(max_length=256)),
                ('school_name_cn', models.CharField(max_length=256)),
                ('short_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('full_name', models.CharField(max_length=256)),
                ('related_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='admissions.university', verbose_name='related_university')),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.IntegerField(choices=[(0, '045: 数学系'), (1, '046: 计算与应用数学系'), (2, '047: 概率统计系'), (3, '002: 物理学系'), (4, '004: 近代物理系'), (5, '022: 天文学系'), (6, '038: 光学与光学工程系'), (7, '048: 工程与应用物理系'), (8, '015: 工商管理系'), (9, '016: 管理科学系'), (10, '017: 统计与金融系'), (11, '034: MBA中心'), (12, '035: MPA中心'), (13, '039: EMBA'), (14, '003: 化学物理系'), (15, '012: 应用化学系'), (16, '014: 材料科学与工程系'), (17, '019: 化学系'), (18, '020: 高分子科学与工程系'), (19, '008: 分子生物学与细胞生物学系'), (20, '021: 神经生物学与生物物理学系'), (21, '031: 系统生物学系'), (22, '032: 医药生物技术系'), (23, '071: 地球物理与行星科学技术系'), (24, '072: 地球化学与环境科学系'), (25, '005: 近代力学系'), (26, '009: 精密机械与精密仪器系'), (27, '013: 热科学和能源工程系'), (28, '030: 安全科学与工程系'), (29, '006: 电子工程与信息科学系'), (30, '010: 自动化系'), (31, '023: 电子科学与技术系'), (32, '033: 信息安全'), (33, '018: 外语系'), (34, '024: 科技史与科技考古系'), (35, '025: 科技传播与科技政策系'), (36, '055: 科技哲学系'), (37, '056: 心理学系'), (38, '011: 计算机科学与技术系'), (39, '044: 物流工程硕士中心')], null=True)),
                ('gpa', models.FloatField()),
                ('TOEFL', models.CharField(max_length=256)),
                ('GRE', models.CharField(max_length=256)),
                ('researchSpec', models.TextField(blank=True, max_length=1024, null=True)),
                ('referSpec', models.TextField(blank=True, max_length=1024, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'ms')], null=True), blank=True, default=list, null=True, size=None)),
                ('summary', models.TextField(max_length=1024)),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background', to=settings.AUTH_USER_MODEL, verbose_name='related user')),
            ],
        ),
        migrations.CreateModel(
            name='Admissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('enrolledSemester', models.CharField(max_length=256)),
                ('comments', models.TextField(max_length=1024)),
                ('related_background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.background', verbose_name='related_background')),
                ('related_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.program', verbose_name='related program')),
                ('related_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.university', verbose_name='related university')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to=settings.AUTH_USER_MODEL, verbose_name='related user')),
            ],
        ),
    ]
