# Generated by Django 3.1.7 on 2021-04-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissions',
            name='tag',
        ),
        migrations.AddField(
            model_name='admissions',
            name='related_background',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admissions.background', verbose_name='related_background'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='comments',
            field=models.TextField(max_length=1024),
        ),
    ]
