# Generated by Django 3.1.7 on 2021-05-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
