# Generated by Django 3.1.7 on 2021-05-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='admissions',
            unique_together=set(),
        ),
    ]
