# Generated by Django 3.1.7 on 2021-05-12 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissions',
            name='upvoted',
            field=models.ManyToManyField(blank=True, null=True, related_name='admissions_upvoted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admissions',
            name='upvoted_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='background',
            name='upvoted',
            field=models.ManyToManyField(blank=True, null=True, related_name='background_upvoted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='background',
            name='upvoted_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
