# Generated by Django 3.1.7 on 2021-03-29 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissions',
            name='program',
        ),
        migrations.RemoveField(
            model_name='admissions',
            name='university',
        ),
        migrations.AddField(
            model_name='admissions',
            name='related_program',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admissions.program', verbose_name='related program'),
        ),
        migrations.AddField(
            model_name='admissions',
            name='related_university',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='admissions.university', verbose_name='related university'),
        ),
    ]
