# Generated by Django 3.1.7 on 2021-04-16 08:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='background',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('top1%', 'top1%'), ('top5%', 'top5%'), ('top10%', 'top10%'), ('top30%', 'top30%'), ('top50%', 'top50%'), ('else', 'else'), ('oversea_refer', 'oversea_refer'), ('connection', 'connection'), ('oversea_research', 'oversea_research'), ('paper', 'paper'), ('first_author', 'first_author'), ('internship', 'internship'), ('ad', 'ad'), ('rej', 'rej'), ('ms', 'ms'), ('phd', 'phd'), ('ms_phd', 'ms_phd')], max_length=255, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
