# Generated by Django 4.0.6 on 2022-07-26 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissions',
            options={'verbose_name': '录取汇报', 'verbose_name_plural': '录取汇报'},
        ),
        migrations.AlterModelOptions(
            name='background',
            options={'verbose_name': '经历', 'verbose_name_plural': '经历'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': '学校', 'verbose_name_plural': '学校'},
        ),
        migrations.AlterField(
            model_name='admissions',
            name='comments',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='项目申请经验'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='enrolledSemester',
            field=models.CharField(max_length=255, verbose_name='申请学年'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='related_background',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.background', verbose_name='经历'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='related_program',
            field=models.CharField(max_length=255, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='related_university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.university', verbose_name='学校'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='result',
            field=models.BooleanField(verbose_name='是否成功'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='summary',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='总结'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='upvoted',
            field=models.ManyToManyField(blank=True, related_name='admissions_upvoted_by', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户名单'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='upvoted_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='background',
            name='GRE',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='GRE'),
        ),
        migrations.AlterField(
            model_name='background',
            name='TOEFL',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TOEFL'),
        ),
        migrations.AlterField(
            model_name='background',
            name='apply_for',
            field=models.CharField(blank=True, choices=[('ms', 'ms'), ('phd', 'phd'), ('ms_phd', 'ms_phd')], max_length=255, null=True, verbose_name='申请学位'),
        ),
        migrations.AlterField(
            model_name='background',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='申请方向思考'),
        ),
        migrations.AlterField(
            model_name='background',
            name='gpa',
            field=models.FloatField(blank=True, null=True, verbose_name='绩点'),
        ),
        migrations.AlterField(
            model_name='background',
            name='major',
            field=models.CharField(choices=[('045', '045: 数学系'), ('046', '046: 计算与应用数学系'), ('047', '047: 概率统计系'), ('002', '002: 物理学系'), ('004', '004: 近代物理系'), ('022', '022: 天文学系'), ('038', '038: 光学与光学工程系'), ('048', '048: 工程与应用物理系'), ('015', '015: 工商管理系'), ('016', '016: 管理科学系'), ('017', '017: 统计与金融系'), ('034', '034: MBA中心'), ('035', '035: MPA中心'), ('039', '039: EMBA'), ('003', '003: 化学物理系'), ('012', '012: 应用化学系'), ('014', '014: 材料科学与工程系'), ('019', '019: 化学系'), ('020', '020: 高分子科学与工程系'), ('008', '008: 分子生物学与细胞生物学系'), ('021', '021: 神经生物学与生物物理学系'), ('031', '031: 系统生物学系'), ('032', '032: 医药生物技术系'), ('071', '071: 地球物理与行星科学技术系'), ('072', '072: 地球化学与环境科学系'), ('005', '005: 近代力学系'), ('009', '009: 精密机械与精密仪器系'), ('013', '013: 热科学和能源工程系'), ('030', '030: 安全科学与工程系'), ('006', '006: 电子工程与信息科学系'), ('010', '010: 自动化系'), ('023', '023: 电子科学与技术系'), ('033', '033: 信息安全'), ('018', '018: 外语系'), ('024', '024: 科技史与科技考古系'), ('025', '025: 科技传播与科技政策系'), ('055', '055: 科技哲学系'), ('056', '056: 心理学系'), ('011', '011: 计算机科学与技术系'), ('044', '044: 物流工程硕士中心')], max_length=255, null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='background',
            name='rank',
            field=models.CharField(blank=True, choices=[('top1%', 'top1%'), ('top5%', 'top5%'), ('top10%', 'top10%'), ('top20%', 'top20%'), ('top30%', 'top30%'), ('top50%', 'top50%'), ('else', 'else')], max_length=255, null=True, verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='background',
            name='referSpec',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='推荐信'),
        ),
        migrations.AlterField(
            model_name='background',
            name='related_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='background',
            name='researchSpec',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='科研经历'),
        ),
        migrations.AlterField(
            model_name='background',
            name='score',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='其他分数'),
        ),
        migrations.AlterField(
            model_name='background',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='申请感言'),
        ),
        migrations.AlterField(
            model_name='background',
            name='upvoted',
            field=models.ManyToManyField(blank=True, related_name='background_upvoted_by', to=settings.AUTH_USER_MODEL, verbose_name='点赞人'),
        ),
        migrations.AlterField(
            model_name='background',
            name='upvoted_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='internbackground',
            name='upvoted',
            field=models.ManyToManyField(blank=True, related_name='internbackground_upvoted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internship',
            name='upvoted',
            field=models.ManyToManyField(blank=True, related_name='internship_upvoted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='university',
            name='area',
            field=models.CharField(max_length=256, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='university',
            name='school_name',
            field=models.CharField(max_length=256, verbose_name='学校名'),
        ),
        migrations.AlterField(
            model_name='university',
            name='school_name_cn',
            field=models.CharField(max_length=256, verbose_name='学校中文名'),
        ),
        migrations.AlterField(
            model_name='university',
            name='short_name',
            field=models.CharField(max_length=256, verbose_name='学校简称'),
        ),
    ]
