# Generated by Django 3.1.7 on 2021-04-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_auto_20210415_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissions',
            name='related_user',
        ),
    ]
