# Generated by Django 3.1.7 on 2021-04-16 08:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_auto_20210416_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='major',
            field=models.CharField(choices=[('045', '045: 数学系'), ('046', '046: 计算与应用数学系'), ('047', '047: 概率统计系'), ('002', '002: 物理学系'), ('004', '004: 近代物理系'), ('022', '022: 天文学系'), ('038', '038: 光学与光学工程系'), ('048', '048: 工程与应用物理系'), ('015', '015: 工商管理系'), ('016', '016: 管理科学系'), ('017', '017: 统计与金融系'), ('034', '034: MBA中心'), ('035', '035: MPA中心'), ('039', '039: EMBA'), ('003', '003: 化学物理系'), ('012', '012: 应用化学系'), ('014', '014: 材料科学与工程系'), ('019', '019: 化学系'), ('020', '020: 高分子科学与工程系'), ('008', '008: 分子生物学与细胞生物学系'), ('021', '021: 神经生物学与生物物理学系'), ('031', '031: 系统生物学系'), ('032', '032: 医药生物技术系'), ('071', '071: 地球物理与行星科学技术系'), ('072', '072: 地球化学与环境科学系'), ('005', '005: 近代力学系'), ('009', '009: 精密机械与精密仪器系'), ('013', '013: 热科学和能源工程系'), ('030', '030: 安全科学与工程系'), ('006', '006: 电子工程与信息科学系'), ('010', '010: 自动化系'), ('023', '023: 电子科学与技术系'), ('033', '033: 信息安全'), ('018', '018: 外语系'), ('024', '024: 科技史与科技考古系'), ('025', '025: 科技传播与科技政策系'), ('055', '055: 科技哲学系'), ('056', '056: 心理学系'), ('011', '011: 计算机科学与技术系'), ('044', '044: 物流工程硕士中心')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('top1%', 'top1%'), ('top5%', 'top5%'), ('top10%', 'top10%'), ('top30%', 'top30%'), ('top50%', 'top50%'), ('else', 'else'), ('oversea_refer', 'oversea_refer'), ('connection', 'connection'), ('oversea_research', 'oversea_research'), ('paper', 'paper'), ('first_author', 'first_author'), ('internship', 'internship'), ('ms', 'ms'), ('phd', 'phd'), ('ms_phd', 'ms_phd')], max_length=255, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
