# Generated by Django 4.0.6 on 2023-07-22 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0003_auto_20220813_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_program', models.CharField(max_length=255, verbose_name='项目名称')),
                ('result', models.BooleanField(verbose_name='是否成功')),
                ('semester', models.CharField(max_length=255, verbose_name='申请学年')),
                ('comments', models.TextField(blank=True, max_length=1024, null=True, verbose_name='项目申请经验')),
                ('summary', models.TextField(blank=True, max_length=1024, null=True, verbose_name='总结')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('upvoted_count', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('related_background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.background', verbose_name='经历')),
                ('related_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.university', verbose_name='学校')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
                ('upvoted', models.ManyToManyField(blank=True, related_name='research_upvoted_by', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户名单')),
            ],
            options={
                'verbose_name': '暑期研究经历',
                'verbose_name_plural': '暑期研究经历',
            },
        ),
    ]
