# Generated by Django 3.1.7 on 2021-04-15 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0003_remove_admissions_related_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissions',
            name='related_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to='account.user', verbose_name='related user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admissions',
            name='related_background',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.background', verbose_name='related_background'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='related_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.program', verbose_name='related program'),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='related_university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.university', verbose_name='related university'),
        ),
    ]
