# Generated by Django 3.1.7 on 2021-04-17 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0004_auto_20210416_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='related_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background', to=settings.AUTH_USER_MODEL, verbose_name='related user'),
        ),
    ]
