# Generated by Django 4.0.6 on 2023-08-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_alter_background_tags_alter_internbackground_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='GRE',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='当前GRE'),
        ),
        migrations.AddField(
            model_name='research',
            name='TOEFL',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='当前TOEFL'),
        ),
        migrations.AddField(
            model_name='research',
            name='gpa',
            field=models.FloatField(blank=True, null=True, verbose_name='当前绩点'),
        ),
    ]
