# Generated by Django 3.1.7 on 2021-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_auto_20210417_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissions',
            name='summary',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='comments',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
