# Generated by Django 3.1.7 on 2021-04-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_auto_20210417_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='summary',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
