# Generated by Django 3.1.7 on 2021-04-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_auto_20210417_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='comments',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
