# Generated by Django 3.1.7 on 2021-04-19 22:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_auto_20210417_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='rank',
            field=models.CharField(blank=True, choices=[('top1%', 'top1%'), ('top5%', 'top5%'), ('top10%', 'top10%'), ('top20%', 'top20%'), ('top30%', 'top30%'), ('top50%', 'top50%'), ('else', 'else')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('oversea_refer', 'oversea_refer'), ('bigname_refer', 'bigname_refer'), ('connection', 'connection'), ('oversea_research', 'oversea_research'), ('paper', 'paper'), ('first_author', 'first_author'), ('internship', 'internship')], max_length=255, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
