# Generated by Django 3.1.7 on 2021-04-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_auto_20210419_2235'),
        ('admissions', '0008_background_comments'),
    ]

    operations = [
    ]
