# Generated by Django 3.1.7 on 2021-04-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_merge_20210421_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='enrolledSemester',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='admissions',
            name='related_program',
            field=models.CharField(max_length=255),
        ),
    ]
