# Generated by Django 3.1.7 on 2021-04-25 10:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0010_auto_20210425_0926'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='admissions',
            unique_together={('related_user', 'related_program', 'related_university', 'enrolledSemester')},
        ),
    ]
