# Generated by Django 3.1.7 on 2021-04-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_auto_20210425_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissions',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='background',
            name='score',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
