# Generated by Django 3.1.7 on 2021-04-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_auto_20210426_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
