# Generated by Django 3.1.7 on 2021-05-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_post_hash',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_post_on',
        ),
    ]
