# Generated by Django 3.1.7 on 2021-04-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210417_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='gid',
            field=models.CharField(default=1, max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
