# Generated by Django 3.1.7 on 2021-05-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210504_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enrolledYear',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isUndergrad',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
