# Generated by Django 3.1.7 on 2021-04-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicrevision',
            name='is_deleted',
        ),
    ]
