# Generated by Django 3.1.7 on 2021-06-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
        migrations.AddField(
            model_name='topic',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
