# Generated by Django 3.1.7 on 2021-05-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_topic_hit_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicrevision',
            options={'get_latest_by': 'revision_number', 'ordering': ('-created_time',)},
        ),
    ]
