# Generated by Django 3.1.7 on 2021-05-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210508_0232'),
        ('forum', '0004_auto_20210509_0830'),
    ]

    operations = [
    ]
