# Generated by Django 4.0.6 on 2022-07-26 03:31

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('doc_type', models.CharField(choices=[('doc', '文档'), ('todo', '代办'), ('list', '名单'), ('other', '其他')], default='doc', max_length=20, verbose_name='文档类型')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
                ('other_info', models.TextField(max_length=500, verbose_name='其他信息')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档',
            },
        ),
    ]
