# Generated by Django 4.0.6 on 2023-12-10 12:23

import array
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('content', models.TextField()),
                ('images', models.JSONField(default=array.array)),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='comment count')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='visit count')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('liked', models.ManyToManyField(blank=True, related_name='post_liked_by', to=settings.AUTH_USER_MODEL)),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('liked', models.ManyToManyField(blank=True, related_name='comment_liked_by', to=settings.AUTH_USER_MODEL)),
                ('related_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='discussion.comment')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='discussion.post')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
